// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mns_dataextra.proto

package com.mi.milink.sdk.proto;

public final class DataExtraProto {
  private DataExtraProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataExtraOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mi.milink.sdk.proto.DataExtra)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float engineratio = 1;</code>
     *
     * <pre>
     *引擎配置比例,vidyo必须为分母
     * </pre>
     */
    boolean hasEngineratio();
    /**
     * <code>optional float engineratio = 1;</code>
     *
     * <pre>
     *引擎配置比例,vidyo必须为分母
     * </pre>
     */
    float getEngineratio();

    /**
     * <code>optional string engineConfigJson = 5;</code>
     */
    boolean hasEngineConfigJson();
    /**
     * <code>optional string engineConfigJson = 5;</code>
     */
    java.lang.String getEngineConfigJson();
    /**
     * <code>optional string engineConfigJson = 5;</code>
     */
    com.google.protobuf.ByteString
        getEngineConfigJsonBytes();
  }
  /**
   * Protobuf type {@code com.mi.milink.sdk.proto.DataExtra}
   *
   * <pre>
   * 这是一个客户端内部的pb结构，不会在网络上传输
   * 为了方便把sdk的数据透传给app，所以定义了此pb结构
   * 使用一个特殊的cmd=data.extra标示
   * </pre>
   */
  public static final class DataExtra extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mi.milink.sdk.proto.DataExtra)
      DataExtraOrBuilder {
    // Use DataExtra.newBuilder() to construct.
    private DataExtra(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataExtra(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataExtra defaultInstance;
    public static DataExtra getDefaultInstance() {
      return defaultInstance;
    }

    @Override
    public DataExtra getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataExtra(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              engineratio_ = input.readFloat();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              engineConfigJson_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataExtra_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataExtra_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mi.milink.sdk.proto.DataExtraProto.DataExtra.class, com.mi.milink.sdk.proto.DataExtraProto.DataExtra.Builder.class);
    }

    public static com.google.protobuf.Parser<DataExtra> PARSER =
        new com.google.protobuf.AbstractParser<DataExtra>() {
      @Override
    public DataExtra parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataExtra(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataExtra> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENGINERATIO_FIELD_NUMBER = 1;
    private float engineratio_;
    /**
     * <code>optional float engineratio = 1;</code>
     *
     * <pre>
     *引擎配置比例,vidyo必须为分母
     * </pre>
     */
    @Override
    public boolean hasEngineratio() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional float engineratio = 1;</code>
     *
     * <pre>
     *引擎配置比例,vidyo必须为分母
     * </pre>
     */
    @Override
    public float getEngineratio() {
      return engineratio_;
    }

    public static final int ENGINECONFIGJSON_FIELD_NUMBER = 5;
    private java.lang.Object engineConfigJson_;
    /**
     * <code>optional string engineConfigJson = 5;</code>
     */
    @Override
    public boolean hasEngineConfigJson() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string engineConfigJson = 5;</code>
     */
    @Override
    public java.lang.String getEngineConfigJson() {
      java.lang.Object ref = engineConfigJson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          engineConfigJson_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string engineConfigJson = 5;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getEngineConfigJsonBytes() {
      java.lang.Object ref = engineConfigJson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineConfigJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      engineratio_ = 0F;
      engineConfigJson_ = "";
    }
    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, engineratio_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(5, getEngineConfigJsonBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, engineratio_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getEngineConfigJsonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataExtra parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mi.milink.sdk.proto.DataExtraProto.DataExtra prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mi.milink.sdk.proto.DataExtra}
     *
     * <pre>
     * 这是一个客户端内部的pb结构，不会在网络上传输
     * 为了方便把sdk的数据透传给app，所以定义了此pb结构
     * 使用一个特殊的cmd=data.extra标示
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mi.milink.sdk.proto.DataExtra)
        com.mi.milink.sdk.proto.DataExtraProto.DataExtraOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataExtra_descriptor;
      }

      @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataExtra_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mi.milink.sdk.proto.DataExtraProto.DataExtra.class, com.mi.milink.sdk.proto.DataExtraProto.DataExtra.Builder.class);
      }

      // Construct using com.mi.milink.sdk.proto.DataExtraProto.DataExtra.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
    public Builder clear() {
        super.clear();
        engineratio_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        engineConfigJson_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
    public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
    public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataExtra_descriptor;
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataExtra getDefaultInstanceForType() {
        return com.mi.milink.sdk.proto.DataExtraProto.DataExtra.getDefaultInstance();
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataExtra build() {
        com.mi.milink.sdk.proto.DataExtraProto.DataExtra result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataExtra buildPartial() {
        com.mi.milink.sdk.proto.DataExtraProto.DataExtra result = new com.mi.milink.sdk.proto.DataExtraProto.DataExtra(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.engineratio_ = engineratio_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.engineConfigJson_ = engineConfigJson_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mi.milink.sdk.proto.DataExtraProto.DataExtra) {
          return mergeFrom((com.mi.milink.sdk.proto.DataExtraProto.DataExtra)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mi.milink.sdk.proto.DataExtraProto.DataExtra other) {
        if (other == com.mi.milink.sdk.proto.DataExtraProto.DataExtra.getDefaultInstance()) return this;
        if (other.hasEngineratio()) {
          setEngineratio(other.getEngineratio());
        }
        if (other.hasEngineConfigJson()) {
          bitField0_ |= 0x00000002;
          engineConfigJson_ = other.engineConfigJson_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
    public final boolean isInitialized() {
        return true;
      }

      @Override
    public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mi.milink.sdk.proto.DataExtraProto.DataExtra parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mi.milink.sdk.proto.DataExtraProto.DataExtra) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float engineratio_ ;
      /**
       * <code>optional float engineratio = 1;</code>
       *
       * <pre>
       *引擎配置比例,vidyo必须为分母
       * </pre>
       */
      @Override
    public boolean hasEngineratio() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional float engineratio = 1;</code>
       *
       * <pre>
       *引擎配置比例,vidyo必须为分母
       * </pre>
       */
      @Override
    public float getEngineratio() {
        return engineratio_;
      }
      /**
       * <code>optional float engineratio = 1;</code>
       *
       * <pre>
       *引擎配置比例,vidyo必须为分母
       * </pre>
       */
      public Builder setEngineratio(float value) {
        bitField0_ |= 0x00000001;
        engineratio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float engineratio = 1;</code>
       *
       * <pre>
       *引擎配置比例,vidyo必须为分母
       * </pre>
       */
      public Builder clearEngineratio() {
        bitField0_ = (bitField0_ & ~0x00000001);
        engineratio_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object engineConfigJson_ = "";
      /**
       * <code>optional string engineConfigJson = 5;</code>
       */
      @Override
    public boolean hasEngineConfigJson() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string engineConfigJson = 5;</code>
       */
      @Override
    public java.lang.String getEngineConfigJson() {
        java.lang.Object ref = engineConfigJson_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            engineConfigJson_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string engineConfigJson = 5;</code>
       */
      @Override
    public com.google.protobuf.ByteString
          getEngineConfigJsonBytes() {
        java.lang.Object ref = engineConfigJson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          engineConfigJson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string engineConfigJson = 5;</code>
       */
      public Builder setEngineConfigJson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        engineConfigJson_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string engineConfigJson = 5;</code>
       */
      public Builder clearEngineConfigJson() {
        bitField0_ = (bitField0_ & ~0x00000002);
        engineConfigJson_ = getDefaultInstance().getEngineConfigJson();
        onChanged();
        return this;
      }
      /**
       * <code>optional string engineConfigJson = 5;</code>
       */
      public Builder setEngineConfigJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        engineConfigJson_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mi.milink.sdk.proto.DataExtra)
    }

    static {
      defaultInstance = new DataExtra(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mi.milink.sdk.proto.DataExtra)
  }

  public interface DataClientIpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mi.milink.sdk.proto.DataClientIp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string clientIp = 1;</code>
     */
    boolean hasClientIp();
    /**
     * <code>optional string clientIp = 1;</code>
     */
    java.lang.String getClientIp();
    /**
     * <code>optional string clientIp = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIpBytes();

    /**
     * <code>optional string clientIpIsp = 2;</code>
     */
    boolean hasClientIpIsp();
    /**
     * <code>optional string clientIpIsp = 2;</code>
     */
    java.lang.String getClientIpIsp();
    /**
     * <code>optional string clientIpIsp = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientIpIspBytes();
  }
  /**
   * Protobuf type {@code com.mi.milink.sdk.proto.DataClientIp}
   */
  public static final class DataClientIp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mi.milink.sdk.proto.DataClientIp)
      DataClientIpOrBuilder {
    // Use DataClientIp.newBuilder() to construct.
    private DataClientIp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataClientIp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataClientIp defaultInstance;
    public static DataClientIp getDefaultInstance() {
      return defaultInstance;
    }

    @Override
    public DataClientIp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataClientIp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              clientIp_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              clientIpIsp_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataClientIp_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataClientIp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mi.milink.sdk.proto.DataExtraProto.DataClientIp.class, com.mi.milink.sdk.proto.DataExtraProto.DataClientIp.Builder.class);
    }

    public static com.google.protobuf.Parser<DataClientIp> PARSER =
        new com.google.protobuf.AbstractParser<DataClientIp>() {
      @Override
    public DataClientIp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataClientIp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataClientIp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CLIENTIP_FIELD_NUMBER = 1;
    private java.lang.Object clientIp_;
    /**
     * <code>optional string clientIp = 1;</code>
     */
    @Override
    public boolean hasClientIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string clientIp = 1;</code>
     */
    @Override
    public java.lang.String getClientIp() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientIp = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getClientIpBytes() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTIPISP_FIELD_NUMBER = 2;
    private java.lang.Object clientIpIsp_;
    /**
     * <code>optional string clientIpIsp = 2;</code>
     */
    @Override
    public boolean hasClientIpIsp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string clientIpIsp = 2;</code>
     */
    @Override
    public java.lang.String getClientIpIsp() {
      java.lang.Object ref = clientIpIsp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientIpIsp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientIpIsp = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getClientIpIspBytes() {
      java.lang.Object ref = clientIpIsp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIpIsp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      clientIp_ = "";
      clientIpIsp_ = "";
    }
    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClientIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClientIpIspBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClientIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClientIpIspBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mi.milink.sdk.proto.DataExtraProto.DataClientIp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mi.milink.sdk.proto.DataClientIp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mi.milink.sdk.proto.DataClientIp)
        com.mi.milink.sdk.proto.DataExtraProto.DataClientIpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataClientIp_descriptor;
      }

      @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataClientIp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mi.milink.sdk.proto.DataExtraProto.DataClientIp.class, com.mi.milink.sdk.proto.DataExtraProto.DataClientIp.Builder.class);
      }

      // Construct using com.mi.milink.sdk.proto.DataExtraProto.DataClientIp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
    public Builder clear() {
        super.clear();
        clientIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clientIpIsp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
    public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
    public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataClientIp_descriptor;
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataClientIp getDefaultInstanceForType() {
        return com.mi.milink.sdk.proto.DataExtraProto.DataClientIp.getDefaultInstance();
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataClientIp build() {
        com.mi.milink.sdk.proto.DataExtraProto.DataClientIp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataClientIp buildPartial() {
        com.mi.milink.sdk.proto.DataExtraProto.DataClientIp result = new com.mi.milink.sdk.proto.DataExtraProto.DataClientIp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientIp_ = clientIp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientIpIsp_ = clientIpIsp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mi.milink.sdk.proto.DataExtraProto.DataClientIp) {
          return mergeFrom((com.mi.milink.sdk.proto.DataExtraProto.DataClientIp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mi.milink.sdk.proto.DataExtraProto.DataClientIp other) {
        if (other == com.mi.milink.sdk.proto.DataExtraProto.DataClientIp.getDefaultInstance()) return this;
        if (other.hasClientIp()) {
          bitField0_ |= 0x00000001;
          clientIp_ = other.clientIp_;
          onChanged();
        }
        if (other.hasClientIpIsp()) {
          bitField0_ |= 0x00000002;
          clientIpIsp_ = other.clientIpIsp_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
    public final boolean isInitialized() {
        return true;
      }

      @Override
    public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mi.milink.sdk.proto.DataExtraProto.DataClientIp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mi.milink.sdk.proto.DataExtraProto.DataClientIp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object clientIp_ = "";
      /**
       * <code>optional string clientIp = 1;</code>
       */
      @Override
    public boolean hasClientIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string clientIp = 1;</code>
       */
      @Override
    public java.lang.String getClientIp() {
        java.lang.Object ref = clientIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientIp = 1;</code>
       */
      @Override
    public com.google.protobuf.ByteString
          getClientIpBytes() {
        java.lang.Object ref = clientIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientIp = 1;</code>
       */
      public Builder setClientIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientIp = 1;</code>
       */
      public Builder clearClientIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientIp_ = getDefaultInstance().getClientIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientIp = 1;</code>
       */
      public Builder setClientIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientIpIsp_ = "";
      /**
       * <code>optional string clientIpIsp = 2;</code>
       */
      @Override
    public boolean hasClientIpIsp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string clientIpIsp = 2;</code>
       */
      @Override
    public java.lang.String getClientIpIsp() {
        java.lang.Object ref = clientIpIsp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientIpIsp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientIpIsp = 2;</code>
       */
      @Override
    public com.google.protobuf.ByteString
          getClientIpIspBytes() {
        java.lang.Object ref = clientIpIsp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIpIsp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientIpIsp = 2;</code>
       */
      public Builder setClientIpIsp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientIpIsp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientIpIsp = 2;</code>
       */
      public Builder clearClientIpIsp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientIpIsp_ = getDefaultInstance().getClientIpIsp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientIpIsp = 2;</code>
       */
      public Builder setClientIpIspBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientIpIsp_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mi.milink.sdk.proto.DataClientIp)
    }

    static {
      defaultInstance = new DataClientIp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mi.milink.sdk.proto.DataClientIp)
  }

  public interface DataAnonymousWidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mi.milink.sdk.proto.DataAnonymousWid)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 wid = 1;</code>
     */
    boolean hasWid();
    /**
     * <code>optional uint64 wid = 1;</code>
     */
    long getWid();
  }
  /**
   * Protobuf type {@code com.mi.milink.sdk.proto.DataAnonymousWid}
   */
  public static final class DataAnonymousWid extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mi.milink.sdk.proto.DataAnonymousWid)
      DataAnonymousWidOrBuilder {
    // Use DataAnonymousWid.newBuilder() to construct.
    private DataAnonymousWid(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataAnonymousWid(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataAnonymousWid defaultInstance;
    public static DataAnonymousWid getDefaultInstance() {
      return defaultInstance;
    }

    @Override
    public DataAnonymousWid getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataAnonymousWid(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              wid_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid.class, com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid.Builder.class);
    }

    public static com.google.protobuf.Parser<DataAnonymousWid> PARSER =
        new com.google.protobuf.AbstractParser<DataAnonymousWid>() {
      @Override
    public DataAnonymousWid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataAnonymousWid(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataAnonymousWid> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int WID_FIELD_NUMBER = 1;
    private long wid_;
    /**
     * <code>optional uint64 wid = 1;</code>
     */
    @Override
    public boolean hasWid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 wid = 1;</code>
     */
    @Override
    public long getWid() {
      return wid_;
    }

    private void initFields() {
      wid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, wid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, wid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mi.milink.sdk.proto.DataAnonymousWid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mi.milink.sdk.proto.DataAnonymousWid)
        com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_descriptor;
      }

      @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid.class, com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid.Builder.class);
      }

      // Construct using com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
    public Builder clear() {
        super.clear();
        wid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
    public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
    public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_descriptor;
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid getDefaultInstanceForType() {
        return com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid.getDefaultInstance();
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid build() {
        com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid buildPartial() {
        com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid result = new com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.wid_ = wid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid) {
          return mergeFrom((com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid other) {
        if (other == com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid.getDefaultInstance()) return this;
        if (other.hasWid()) {
          setWid(other.getWid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
    public final boolean isInitialized() {
        return true;
      }

      @Override
    public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mi.milink.sdk.proto.DataExtraProto.DataAnonymousWid) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long wid_ ;
      /**
       * <code>optional uint64 wid = 1;</code>
       */
      @Override
    public boolean hasWid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 wid = 1;</code>
       */
      @Override
    public long getWid() {
        return wid_;
      }
      /**
       * <code>optional uint64 wid = 1;</code>
       */
      public Builder setWid(long value) {
        bitField0_ |= 0x00000001;
        wid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 wid = 1;</code>
       */
      public Builder clearWid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        wid_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mi.milink.sdk.proto.DataAnonymousWid)
    }

    static {
      defaultInstance = new DataAnonymousWid(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mi.milink.sdk.proto.DataAnonymousWid)
  }

  public interface DataLoglevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mi.milink.sdk.proto.DataLoglevel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 loglevel = 1;</code>
     *
     * <pre>
     * 日志级别
     * </pre>
     */
    boolean hasLoglevel();
    /**
     * <code>optional uint32 loglevel = 1;</code>
     *
     * <pre>
     * 日志级别
     * </pre>
     */
    int getLoglevel();

    /**
     * <code>optional uint32 timeLong = 2;</code>
     *
     * <pre>
     *时长
     * </pre>
     */
    boolean hasTimeLong();
    /**
     * <code>optional uint32 timeLong = 2;</code>
     *
     * <pre>
     *时长
     * </pre>
     */
    int getTimeLong();
  }
  /**
   * Protobuf type {@code com.mi.milink.sdk.proto.DataLoglevel}
   */
  public static final class DataLoglevel extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mi.milink.sdk.proto.DataLoglevel)
      DataLoglevelOrBuilder {
    // Use DataLoglevel.newBuilder() to construct.
    private DataLoglevel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataLoglevel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataLoglevel defaultInstance;
    public static DataLoglevel getDefaultInstance() {
      return defaultInstance;
    }

    @Override
    public DataLoglevel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataLoglevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              loglevel_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timeLong_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataLoglevel_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataLoglevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel.class, com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel.Builder.class);
    }

    public static com.google.protobuf.Parser<DataLoglevel> PARSER =
        new com.google.protobuf.AbstractParser<DataLoglevel>() {
      @Override
    public DataLoglevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataLoglevel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DataLoglevel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LOGLEVEL_FIELD_NUMBER = 1;
    private int loglevel_;
    /**
     * <code>optional uint32 loglevel = 1;</code>
     *
     * <pre>
     * 日志级别
     * </pre>
     */
    @Override
    public boolean hasLoglevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 loglevel = 1;</code>
     *
     * <pre>
     * 日志级别
     * </pre>
     */
    @Override
    public int getLoglevel() {
      return loglevel_;
    }

    public static final int TIMELONG_FIELD_NUMBER = 2;
    private int timeLong_;
    /**
     * <code>optional uint32 timeLong = 2;</code>
     *
     * <pre>
     *时长
     * </pre>
     */
    @Override
    public boolean hasTimeLong() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 timeLong = 2;</code>
     *
     * <pre>
     *时长
     * </pre>
     */
    @Override
    public int getTimeLong() {
      return timeLong_;
    }

    private void initFields() {
      loglevel_ = 0;
      timeLong_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, loglevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, timeLong_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, loglevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, timeLong_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mi.milink.sdk.proto.DataLoglevel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mi.milink.sdk.proto.DataLoglevel)
        com.mi.milink.sdk.proto.DataExtraProto.DataLoglevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataLoglevel_descriptor;
      }

      @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataLoglevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel.class, com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel.Builder.class);
      }

      // Construct using com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
    public Builder clear() {
        super.clear();
        loglevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timeLong_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
    public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
    public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mi.milink.sdk.proto.DataExtraProto.internal_static_com_mi_milink_sdk_proto_DataLoglevel_descriptor;
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel getDefaultInstanceForType() {
        return com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel.getDefaultInstance();
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel build() {
        com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
    public com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel buildPartial() {
        com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel result = new com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loglevel_ = loglevel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timeLong_ = timeLong_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel) {
          return mergeFrom((com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel other) {
        if (other == com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel.getDefaultInstance()) return this;
        if (other.hasLoglevel()) {
          setLoglevel(other.getLoglevel());
        }
        if (other.hasTimeLong()) {
          setTimeLong(other.getTimeLong());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
    public final boolean isInitialized() {
        return true;
      }

      @Override
    public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mi.milink.sdk.proto.DataExtraProto.DataLoglevel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int loglevel_ ;
      /**
       * <code>optional uint32 loglevel = 1;</code>
       *
       * <pre>
       * 日志级别
       * </pre>
       */
      @Override
    public boolean hasLoglevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 loglevel = 1;</code>
       *
       * <pre>
       * 日志级别
       * </pre>
       */
      @Override
    public int getLoglevel() {
        return loglevel_;
      }
      /**
       * <code>optional uint32 loglevel = 1;</code>
       *
       * <pre>
       * 日志级别
       * </pre>
       */
      public Builder setLoglevel(int value) {
        bitField0_ |= 0x00000001;
        loglevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 loglevel = 1;</code>
       *
       * <pre>
       * 日志级别
       * </pre>
       */
      public Builder clearLoglevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loglevel_ = 0;
        onChanged();
        return this;
      }

      private int timeLong_ ;
      /**
       * <code>optional uint32 timeLong = 2;</code>
       *
       * <pre>
       *时长
       * </pre>
       */
      @Override
    public boolean hasTimeLong() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 timeLong = 2;</code>
       *
       * <pre>
       *时长
       * </pre>
       */
      @Override
    public int getTimeLong() {
        return timeLong_;
      }
      /**
       * <code>optional uint32 timeLong = 2;</code>
       *
       * <pre>
       *时长
       * </pre>
       */
      public Builder setTimeLong(int value) {
        bitField0_ |= 0x00000002;
        timeLong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 timeLong = 2;</code>
       *
       * <pre>
       *时长
       * </pre>
       */
      public Builder clearTimeLong() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timeLong_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mi.milink.sdk.proto.DataLoglevel)
    }

    static {
      defaultInstance = new DataLoglevel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mi.milink.sdk.proto.DataLoglevel)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mi_milink_sdk_proto_DataExtra_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mi_milink_sdk_proto_DataExtra_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mi_milink_sdk_proto_DataClientIp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mi_milink_sdk_proto_DataClientIp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mi_milink_sdk_proto_DataLoglevel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mi_milink_sdk_proto_DataLoglevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023mns_dataextra.proto\022\027com.mi.milink.sdk" +
      ".proto\":\n\tDataExtra\022\023\n\013engineratio\030\001 \001(\002" +
      "\022\030\n\020engineConfigJson\030\005 \001(\t\"5\n\014DataClient" +
      "Ip\022\020\n\010clientIp\030\001 \001(\t\022\023\n\013clientIpIsp\030\002 \001(" +
      "\t\"\037\n\020DataAnonymousWid\022\013\n\003wid\030\001 \001(\004\"2\n\014Da" +
      "taLoglevel\022\020\n\010loglevel\030\001 \001(\r\022\020\n\010timeLong" +
      "\030\002 \001(\rB)\n\027com.mi.milink.sdk.protoB\016DataE" +
      "xtraProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          @Override
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mi_milink_sdk_proto_DataExtra_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mi_milink_sdk_proto_DataExtra_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mi_milink_sdk_proto_DataExtra_descriptor,
        new java.lang.String[] { "Engineratio", "EngineConfigJson", });
    internal_static_com_mi_milink_sdk_proto_DataClientIp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mi_milink_sdk_proto_DataClientIp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mi_milink_sdk_proto_DataClientIp_descriptor,
        new java.lang.String[] { "ClientIp", "ClientIpIsp", });
    internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mi_milink_sdk_proto_DataAnonymousWid_descriptor,
        new java.lang.String[] { "Wid", });
    internal_static_com_mi_milink_sdk_proto_DataLoglevel_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_mi_milink_sdk_proto_DataLoglevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mi_milink_sdk_proto_DataLoglevel_descriptor,
        new java.lang.String[] { "Loglevel", "TimeLong", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
