// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/mns_downstream.proto

package com.mi.milink.sdk.proto;

public final class DownstreamPacketProto {
  private DownstreamPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DownstreamPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mi.milink.sdk.proto.DownstreamPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 seq = 1;</code>
     *
     * <pre>
     *序列号
     * </pre>
     */
    boolean hasSeq();
    /**
     * <code>optional uint32 seq = 1;</code>
     *
     * <pre>
     *序列号
     * </pre>
     */
    int getSeq();

    /**
     * <code>optional uint64 miUin = 2;</code>
     *
     * <pre>
     *小米用户ID
     * </pre>
     */
    boolean hasMiUin();
    /**
     * <code>optional uint64 miUin = 2;</code>
     *
     * <pre>
     *小米用户ID
     * </pre>
     */
    long getMiUin();

    /**
     * <code>optional sint32 mnsCode = 3;</code>
     *
     * <pre>
     *mns内部返回码 业务不用设此值
     * </pre>
     */
    boolean hasMnsCode();
    /**
     * <code>optional sint32 mnsCode = 3;</code>
     *
     * <pre>
     *mns内部返回码 业务不用设此值
     * </pre>
     */
    int getMnsCode();

    /**
     * <code>optional sint32 busiCode = 4;</code>
     *
     * <pre>
     *业务返回码 由业务传入。用于mns统计监控使用
     * </pre>
     */
    boolean hasBusiCode();
    /**
     * <code>optional sint32 busiCode = 4;</code>
     *
     * <pre>
     *业务返回码 由业务传入。用于mns统计监控使用
     * </pre>
     */
    int getBusiCode();

    /**
     * <code>optional string serviceCmd = 5;</code>
     *
     * <pre>
     *命令字
     * </pre>
     */
    boolean hasServiceCmd();
    /**
     * <code>optional string serviceCmd = 5;</code>
     *
     * <pre>
     *命令字
     * </pre>
     */
    java.lang.String getServiceCmd();
    /**
     * <code>optional string serviceCmd = 5;</code>
     *
     * <pre>
     *命令字
     * </pre>
     */
    com.google.protobuf.ByteString
        getServiceCmdBytes();

    /**
     * <code>optional bytes busiBuff = 6;</code>
     *
     * <pre>
     *业务数据包
     * </pre>
     */
    boolean hasBusiBuff();
    /**
     * <code>optional bytes busiBuff = 6;</code>
     *
     * <pre>
     *业务数据包
     * </pre>
     */
    com.google.protobuf.ByteString getBusiBuff();

    /**
     * <code>optional bytes extra = 7;</code>
     *
     * <pre>
     *mns附加信息
     * </pre>
     */
    boolean hasExtra();
    /**
     * <code>optional bytes extra = 7;</code>
     *
     * <pre>
     *mns附加信息
     * </pre>
     */
    com.google.protobuf.ByteString getExtra();

    /**
     * <code>optional string mnsErrMsg = 8;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    boolean hasMnsErrMsg();
    /**
     * <code>optional string mnsErrMsg = 8;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    java.lang.String getMnsErrMsg();
    /**
     * <code>optional string mnsErrMsg = 8;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMnsErrMsgBytes();

    /**
     * <code>optional string miUid = 9;</code>
     *
     * <pre>
     *string 类型的uin
     * </pre>
     */
    boolean hasMiUid();
    /**
     * <code>optional string miUid = 9;</code>
     *
     * <pre>
     *string 类型的uin
     * </pre>
     */
    java.lang.String getMiUid();
    /**
     * <code>optional string miUid = 9;</code>
     *
     * <pre>
     *string 类型的uin
     * </pre>
     */
    com.google.protobuf.ByteString
        getMiUidBytes();

    /**
     * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
     *
     * <pre>
     *BusiBuff的加压控制
     * </pre>
     */
    boolean hasBusiControl();
    /**
     * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
     *
     * <pre>
     *BusiBuff的加压控制
     * </pre>
     */
    com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl getBusiControl();
    /**
     * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
     *
     * <pre>
     *BusiBuff的加压控制
     * </pre>
     */
    com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControlOrBuilder getBusiControlOrBuilder();
  }
  /**
   * Protobuf type {@code com.mi.milink.sdk.proto.DownstreamPacket}
   */
  public static final class DownstreamPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mi.milink.sdk.proto.DownstreamPacket)
      DownstreamPacketOrBuilder {
    // Use DownstreamPacket.newBuilder() to construct.
    private DownstreamPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DownstreamPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DownstreamPacket defaultInstance;
    public static DownstreamPacket getDefaultInstance() {
      return defaultInstance;
    }

    @Override
    public DownstreamPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DownstreamPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seq_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              miUin_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              mnsCode_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              busiCode_ = input.readSInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              serviceCmd_ = bs;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              busiBuff_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              extra_ = input.readBytes();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              mnsErrMsg_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              miUid_ = bs;
              break;
            }
            case 82: {
              com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = busiControl_.toBuilder();
              }
              busiControl_ = input.readMessage(com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(busiControl_);
                busiControl_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_DownstreamPacket_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_DownstreamPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket.class, com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<DownstreamPacket> PARSER =
        new com.google.protobuf.AbstractParser<DownstreamPacket>() {
      @Override
    public DownstreamPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DownstreamPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DownstreamPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SEQ_FIELD_NUMBER = 1;
    private int seq_;
    /**
     * <code>optional uint32 seq = 1;</code>
     *
     * <pre>
     *序列号
     * </pre>
     */
    @Override
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 seq = 1;</code>
     *
     * <pre>
     *序列号
     * </pre>
     */
    @Override
    public int getSeq() {
      return seq_;
    }

    public static final int MIUIN_FIELD_NUMBER = 2;
    private long miUin_;
    /**
     * <code>optional uint64 miUin = 2;</code>
     *
     * <pre>
     *小米用户ID
     * </pre>
     */
    @Override
    public boolean hasMiUin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 miUin = 2;</code>
     *
     * <pre>
     *小米用户ID
     * </pre>
     */
    @Override
    public long getMiUin() {
      return miUin_;
    }

    public static final int MNSCODE_FIELD_NUMBER = 3;
    private int mnsCode_;
    /**
     * <code>optional sint32 mnsCode = 3;</code>
     *
     * <pre>
     *mns内部返回码 业务不用设此值
     * </pre>
     */
    @Override
    public boolean hasMnsCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 mnsCode = 3;</code>
     *
     * <pre>
     *mns内部返回码 业务不用设此值
     * </pre>
     */
    @Override
    public int getMnsCode() {
      return mnsCode_;
    }

    public static final int BUSICODE_FIELD_NUMBER = 4;
    private int busiCode_;
    /**
     * <code>optional sint32 busiCode = 4;</code>
     *
     * <pre>
     *业务返回码 由业务传入。用于mns统计监控使用
     * </pre>
     */
    @Override
    public boolean hasBusiCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional sint32 busiCode = 4;</code>
     *
     * <pre>
     *业务返回码 由业务传入。用于mns统计监控使用
     * </pre>
     */
    @Override
    public int getBusiCode() {
      return busiCode_;
    }

    public static final int SERVICECMD_FIELD_NUMBER = 5;
    private java.lang.Object serviceCmd_;
    /**
     * <code>optional string serviceCmd = 5;</code>
     *
     * <pre>
     *命令字
     * </pre>
     */
    @Override
    public boolean hasServiceCmd() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string serviceCmd = 5;</code>
     *
     * <pre>
     *命令字
     * </pre>
     */
    @Override
    public java.lang.String getServiceCmd() {
      java.lang.Object ref = serviceCmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceCmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serviceCmd = 5;</code>
     *
     * <pre>
     *命令字
     * </pre>
     */
    @Override
    public com.google.protobuf.ByteString
        getServiceCmdBytes() {
      java.lang.Object ref = serviceCmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceCmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUSIBUFF_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString busiBuff_;
    /**
     * <code>optional bytes busiBuff = 6;</code>
     *
     * <pre>
     *业务数据包
     * </pre>
     */
    @Override
    public boolean hasBusiBuff() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes busiBuff = 6;</code>
     *
     * <pre>
     *业务数据包
     * </pre>
     */
    @Override
    public com.google.protobuf.ByteString getBusiBuff() {
      return busiBuff_;
    }

    public static final int EXTRA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString extra_;
    /**
     * <code>optional bytes extra = 7;</code>
     *
     * <pre>
     *mns附加信息
     * </pre>
     */
    @Override
    public boolean hasExtra() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes extra = 7;</code>
     *
     * <pre>
     *mns附加信息
     * </pre>
     */
    @Override
    public com.google.protobuf.ByteString getExtra() {
      return extra_;
    }

    public static final int MNSERRMSG_FIELD_NUMBER = 8;
    private java.lang.Object mnsErrMsg_;
    /**
     * <code>optional string mnsErrMsg = 8;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    @Override
    public boolean hasMnsErrMsg() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string mnsErrMsg = 8;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    @Override
    public java.lang.String getMnsErrMsg() {
      java.lang.Object ref = mnsErrMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mnsErrMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mnsErrMsg = 8;</code>
     *
     * <pre>
     *错误信息
     * </pre>
     */
    @Override
    public com.google.protobuf.ByteString
        getMnsErrMsgBytes() {
      java.lang.Object ref = mnsErrMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mnsErrMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIUID_FIELD_NUMBER = 9;
    private java.lang.Object miUid_;
    /**
     * <code>optional string miUid = 9;</code>
     *
     * <pre>
     *string 类型的uin
     * </pre>
     */
    @Override
    public boolean hasMiUid() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string miUid = 9;</code>
     *
     * <pre>
     *string 类型的uin
     * </pre>
     */
    @Override
    public java.lang.String getMiUid() {
      java.lang.Object ref = miUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          miUid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string miUid = 9;</code>
     *
     * <pre>
     *string 类型的uin
     * </pre>
     */
    @Override
    public com.google.protobuf.ByteString
        getMiUidBytes() {
      java.lang.Object ref = miUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        miUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUSICONTROL_FIELD_NUMBER = 10;
    private com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl busiControl_;
    /**
     * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
     *
     * <pre>
     *BusiBuff的加压控制
     * </pre>
     */
    @Override
    public boolean hasBusiControl() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
     *
     * <pre>
     *BusiBuff的加压控制
     * </pre>
     */
    @Override
    public com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl getBusiControl() {
      return busiControl_;
    }
    /**
     * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
     *
     * <pre>
     *BusiBuff的加压控制
     * </pre>
     */
    @Override
    public com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControlOrBuilder getBusiControlOrBuilder() {
      return busiControl_;
    }

    private void initFields() {
      seq_ = 0;
      miUin_ = 0L;
      mnsCode_ = 0;
      busiCode_ = 0;
      serviceCmd_ = "";
      busiBuff_ = com.google.protobuf.ByteString.EMPTY;
      extra_ = com.google.protobuf.ByteString.EMPTY;
      mnsErrMsg_ = "";
      miUid_ = "";
      busiControl_ = com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, seq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, miUin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, mnsCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(4, busiCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getServiceCmdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, busiBuff_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, extra_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getMnsErrMsgBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getMiUidBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, busiControl_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, seq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, miUin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, mnsCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, busiCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getServiceCmdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, busiBuff_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, extra_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getMnsErrMsgBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMiUidBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, busiControl_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mi.milink.sdk.proto.DownstreamPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mi.milink.sdk.proto.DownstreamPacket)
        com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_DownstreamPacket_descriptor;
      }

      @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_DownstreamPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket.class, com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket.Builder.class);
      }

      // Construct using com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBusiControlFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
    public Builder clear() {
        super.clear();
        seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        miUin_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        mnsCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        busiCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        serviceCmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        busiBuff_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        extra_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        mnsErrMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        miUid_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        if (busiControlBuilder_ == null) {
          busiControl_ = com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.getDefaultInstance();
        } else {
          busiControlBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      @Override
    public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
    public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_DownstreamPacket_descriptor;
      }

      @Override
    public com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket getDefaultInstanceForType() {
        return com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket.getDefaultInstance();
      }

      @Override
    public com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket build() {
        com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
    public com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket buildPartial() {
        com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket result = new com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seq_ = seq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.miUin_ = miUin_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mnsCode_ = mnsCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.busiCode_ = busiCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.serviceCmd_ = serviceCmd_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.busiBuff_ = busiBuff_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.extra_ = extra_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.mnsErrMsg_ = mnsErrMsg_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.miUid_ = miUid_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (busiControlBuilder_ == null) {
          result.busiControl_ = busiControl_;
        } else {
          result.busiControl_ = busiControlBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket) {
          return mergeFrom((com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket other) {
        if (other == com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket.getDefaultInstance()) return this;
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        if (other.hasMiUin()) {
          setMiUin(other.getMiUin());
        }
        if (other.hasMnsCode()) {
          setMnsCode(other.getMnsCode());
        }
        if (other.hasBusiCode()) {
          setBusiCode(other.getBusiCode());
        }
        if (other.hasServiceCmd()) {
          bitField0_ |= 0x00000010;
          serviceCmd_ = other.serviceCmd_;
          onChanged();
        }
        if (other.hasBusiBuff()) {
          setBusiBuff(other.getBusiBuff());
        }
        if (other.hasExtra()) {
          setExtra(other.getExtra());
        }
        if (other.hasMnsErrMsg()) {
          bitField0_ |= 0x00000080;
          mnsErrMsg_ = other.mnsErrMsg_;
          onChanged();
        }
        if (other.hasMiUid()) {
          bitField0_ |= 0x00000100;
          miUid_ = other.miUid_;
          onChanged();
        }
        if (other.hasBusiControl()) {
          mergeBusiControl(other.getBusiControl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
    public final boolean isInitialized() {
        return true;
      }

      @Override
    public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mi.milink.sdk.proto.DownstreamPacketProto.DownstreamPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int seq_ ;
      /**
       * <code>optional uint32 seq = 1;</code>
       *
       * <pre>
       *序列号
       * </pre>
       */
      @Override
    public boolean hasSeq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 seq = 1;</code>
       *
       * <pre>
       *序列号
       * </pre>
       */
      @Override
    public int getSeq() {
        return seq_;
      }
      /**
       * <code>optional uint32 seq = 1;</code>
       *
       * <pre>
       *序列号
       * </pre>
       */
      public Builder setSeq(int value) {
        bitField0_ |= 0x00000001;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 seq = 1;</code>
       *
       * <pre>
       *序列号
       * </pre>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seq_ = 0;
        onChanged();
        return this;
      }

      private long miUin_ ;
      /**
       * <code>optional uint64 miUin = 2;</code>
       *
       * <pre>
       *小米用户ID
       * </pre>
       */
      @Override
    public boolean hasMiUin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 miUin = 2;</code>
       *
       * <pre>
       *小米用户ID
       * </pre>
       */
      @Override
    public long getMiUin() {
        return miUin_;
      }
      /**
       * <code>optional uint64 miUin = 2;</code>
       *
       * <pre>
       *小米用户ID
       * </pre>
       */
      public Builder setMiUin(long value) {
        bitField0_ |= 0x00000002;
        miUin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 miUin = 2;</code>
       *
       * <pre>
       *小米用户ID
       * </pre>
       */
      public Builder clearMiUin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        miUin_ = 0L;
        onChanged();
        return this;
      }

      private int mnsCode_ ;
      /**
       * <code>optional sint32 mnsCode = 3;</code>
       *
       * <pre>
       *mns内部返回码 业务不用设此值
       * </pre>
       */
      @Override
    public boolean hasMnsCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 mnsCode = 3;</code>
       *
       * <pre>
       *mns内部返回码 业务不用设此值
       * </pre>
       */
      @Override
    public int getMnsCode() {
        return mnsCode_;
      }
      /**
       * <code>optional sint32 mnsCode = 3;</code>
       *
       * <pre>
       *mns内部返回码 业务不用设此值
       * </pre>
       */
      public Builder setMnsCode(int value) {
        bitField0_ |= 0x00000004;
        mnsCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 mnsCode = 3;</code>
       *
       * <pre>
       *mns内部返回码 业务不用设此值
       * </pre>
       */
      public Builder clearMnsCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mnsCode_ = 0;
        onChanged();
        return this;
      }

      private int busiCode_ ;
      /**
       * <code>optional sint32 busiCode = 4;</code>
       *
       * <pre>
       *业务返回码 由业务传入。用于mns统计监控使用
       * </pre>
       */
      @Override
    public boolean hasBusiCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional sint32 busiCode = 4;</code>
       *
       * <pre>
       *业务返回码 由业务传入。用于mns统计监控使用
       * </pre>
       */
      @Override
    public int getBusiCode() {
        return busiCode_;
      }
      /**
       * <code>optional sint32 busiCode = 4;</code>
       *
       * <pre>
       *业务返回码 由业务传入。用于mns统计监控使用
       * </pre>
       */
      public Builder setBusiCode(int value) {
        bitField0_ |= 0x00000008;
        busiCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 busiCode = 4;</code>
       *
       * <pre>
       *业务返回码 由业务传入。用于mns统计监控使用
       * </pre>
       */
      public Builder clearBusiCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        busiCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serviceCmd_ = "";
      /**
       * <code>optional string serviceCmd = 5;</code>
       *
       * <pre>
       *命令字
       * </pre>
       */
      @Override
    public boolean hasServiceCmd() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string serviceCmd = 5;</code>
       *
       * <pre>
       *命令字
       * </pre>
       */
      @Override
    public java.lang.String getServiceCmd() {
        java.lang.Object ref = serviceCmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceCmd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serviceCmd = 5;</code>
       *
       * <pre>
       *命令字
       * </pre>
       */
      @Override
    public com.google.protobuf.ByteString
          getServiceCmdBytes() {
        java.lang.Object ref = serviceCmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceCmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serviceCmd = 5;</code>
       *
       * <pre>
       *命令字
       * </pre>
       */
      public Builder setServiceCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serviceCmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceCmd = 5;</code>
       *
       * <pre>
       *命令字
       * </pre>
       */
      public Builder clearServiceCmd() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serviceCmd_ = getDefaultInstance().getServiceCmd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceCmd = 5;</code>
       *
       * <pre>
       *命令字
       * </pre>
       */
      public Builder setServiceCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serviceCmd_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString busiBuff_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes busiBuff = 6;</code>
       *
       * <pre>
       *业务数据包
       * </pre>
       */
      @Override
    public boolean hasBusiBuff() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes busiBuff = 6;</code>
       *
       * <pre>
       *业务数据包
       * </pre>
       */
      @Override
    public com.google.protobuf.ByteString getBusiBuff() {
        return busiBuff_;
      }
      /**
       * <code>optional bytes busiBuff = 6;</code>
       *
       * <pre>
       *业务数据包
       * </pre>
       */
      public Builder setBusiBuff(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        busiBuff_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes busiBuff = 6;</code>
       *
       * <pre>
       *业务数据包
       * </pre>
       */
      public Builder clearBusiBuff() {
        bitField0_ = (bitField0_ & ~0x00000020);
        busiBuff_ = getDefaultInstance().getBusiBuff();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString extra_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes extra = 7;</code>
       *
       * <pre>
       *mns附加信息
       * </pre>
       */
      @Override
    public boolean hasExtra() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes extra = 7;</code>
       *
       * <pre>
       *mns附加信息
       * </pre>
       */
      @Override
    public com.google.protobuf.ByteString getExtra() {
        return extra_;
      }
      /**
       * <code>optional bytes extra = 7;</code>
       *
       * <pre>
       *mns附加信息
       * </pre>
       */
      public Builder setExtra(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes extra = 7;</code>
       *
       * <pre>
       *mns附加信息
       * </pre>
       */
      public Builder clearExtra() {
        bitField0_ = (bitField0_ & ~0x00000040);
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }

      private java.lang.Object mnsErrMsg_ = "";
      /**
       * <code>optional string mnsErrMsg = 8;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      @Override
    public boolean hasMnsErrMsg() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string mnsErrMsg = 8;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      @Override
    public java.lang.String getMnsErrMsg() {
        java.lang.Object ref = mnsErrMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mnsErrMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mnsErrMsg = 8;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      @Override
    public com.google.protobuf.ByteString
          getMnsErrMsgBytes() {
        java.lang.Object ref = mnsErrMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mnsErrMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mnsErrMsg = 8;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder setMnsErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        mnsErrMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mnsErrMsg = 8;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder clearMnsErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000080);
        mnsErrMsg_ = getDefaultInstance().getMnsErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mnsErrMsg = 8;</code>
       *
       * <pre>
       *错误信息
       * </pre>
       */
      public Builder setMnsErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        mnsErrMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object miUid_ = "";
      /**
       * <code>optional string miUid = 9;</code>
       *
       * <pre>
       *string 类型的uin
       * </pre>
       */
      @Override
    public boolean hasMiUid() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string miUid = 9;</code>
       *
       * <pre>
       *string 类型的uin
       * </pre>
       */
      @Override
    public java.lang.String getMiUid() {
        java.lang.Object ref = miUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            miUid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string miUid = 9;</code>
       *
       * <pre>
       *string 类型的uin
       * </pre>
       */
      @Override
    public com.google.protobuf.ByteString
          getMiUidBytes() {
        java.lang.Object ref = miUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          miUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string miUid = 9;</code>
       *
       * <pre>
       *string 类型的uin
       * </pre>
       */
      public Builder setMiUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        miUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string miUid = 9;</code>
       *
       * <pre>
       *string 类型的uin
       * </pre>
       */
      public Builder clearMiUid() {
        bitField0_ = (bitField0_ & ~0x00000100);
        miUid_ = getDefaultInstance().getMiUid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string miUid = 9;</code>
       *
       * <pre>
       *string 类型的uin
       * </pre>
       */
      public Builder setMiUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        miUid_ = value;
        onChanged();
        return this;
      }

      private com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl busiControl_ = com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl, com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.Builder, com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControlOrBuilder> busiControlBuilder_;
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      @Override
    public boolean hasBusiControl() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      @Override
    public com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl getBusiControl() {
        if (busiControlBuilder_ == null) {
          return busiControl_;
        } else {
          return busiControlBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      public Builder setBusiControl(com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl value) {
        if (busiControlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          busiControl_ = value;
          onChanged();
        } else {
          busiControlBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      public Builder setBusiControl(
          com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.Builder builderForValue) {
        if (busiControlBuilder_ == null) {
          busiControl_ = builderForValue.build();
          onChanged();
        } else {
          busiControlBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      public Builder mergeBusiControl(com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl value) {
        if (busiControlBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              busiControl_ != com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.getDefaultInstance()) {
            busiControl_ =
              com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.newBuilder(busiControl_).mergeFrom(value).buildPartial();
          } else {
            busiControl_ = value;
          }
          onChanged();
        } else {
          busiControlBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      public Builder clearBusiControl() {
        if (busiControlBuilder_ == null) {
          busiControl_ = com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.getDefaultInstance();
          onChanged();
        } else {
          busiControlBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      public com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.Builder getBusiControlBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getBusiControlFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      @Override
    public com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControlOrBuilder getBusiControlOrBuilder() {
        if (busiControlBuilder_ != null) {
          return busiControlBuilder_.getMessageOrBuilder();
        } else {
          return busiControl_;
        }
      }
      /**
       * <code>optional .com.mi.milink.sdk.proto.BusiControl busiControl = 10;</code>
       *
       * <pre>
       *BusiBuff的加压控制
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl, com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.Builder, com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControlOrBuilder> 
          getBusiControlFieldBuilder() {
        if (busiControlBuilder_ == null) {
          busiControlBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl, com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControl.Builder, com.mi.milink.sdk.proto.UpstreamPacketProto.BusiControlOrBuilder>(
                  getBusiControl(),
                  getParentForChildren(),
                  isClean());
          busiControl_ = null;
        }
        return busiControlBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.mi.milink.sdk.proto.DownstreamPacket)
    }

    static {
      defaultInstance = new DownstreamPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mi.milink.sdk.proto.DownstreamPacket)
  }

  public interface ExtraInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mi.milink.sdk.proto.ExtraInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool hasClientInfo = 1;</code>
     *
     * <pre>
     * true 代表acc 缓存了 client信息
     * </pre>
     */
    boolean hasHasClientInfo();
    /**
     * <code>optional bool hasClientInfo = 1;</code>
     *
     * <pre>
     * true 代表acc 缓存了 client信息
     * </pre>
     */
    boolean getHasClientInfo();
  }
  /**
   * Protobuf type {@code com.mi.milink.sdk.proto.ExtraInfo}
   */
  public static final class ExtraInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mi.milink.sdk.proto.ExtraInfo)
      ExtraInfoOrBuilder {
    // Use ExtraInfo.newBuilder() to construct.
    private ExtraInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExtraInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExtraInfo defaultInstance;
    public static ExtraInfo getDefaultInstance() {
      return defaultInstance;
    }

    @Override
    public ExtraInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExtraInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hasClientInfo_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_ExtraInfo_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_ExtraInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo.class, com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ExtraInfo> PARSER =
        new com.google.protobuf.AbstractParser<ExtraInfo>() {
      @Override
    public ExtraInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExtraInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExtraInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HASCLIENTINFO_FIELD_NUMBER = 1;
    private boolean hasClientInfo_;
    /**
     * <code>optional bool hasClientInfo = 1;</code>
     *
     * <pre>
     * true 代表acc 缓存了 client信息
     * </pre>
     */
    @Override
    public boolean hasHasClientInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool hasClientInfo = 1;</code>
     *
     * <pre>
     * true 代表acc 缓存了 client信息
     * </pre>
     */
    @Override
    public boolean getHasClientInfo() {
      return hasClientInfo_;
    }

    private void initFields() {
      hasClientInfo_ = false;
    }
    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, hasClientInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, hasClientInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mi.milink.sdk.proto.ExtraInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mi.milink.sdk.proto.ExtraInfo)
        com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_ExtraInfo_descriptor;
      }

      @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_ExtraInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo.class, com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo.Builder.class);
      }

      // Construct using com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
    public Builder clear() {
        super.clear();
        hasClientInfo_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
    public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
    public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mi.milink.sdk.proto.DownstreamPacketProto.internal_static_com_mi_milink_sdk_proto_ExtraInfo_descriptor;
      }

      @Override
    public com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo getDefaultInstanceForType() {
        return com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo.getDefaultInstance();
      }

      @Override
    public com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo build() {
        com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
    public com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo buildPartial() {
        com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo result = new com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hasClientInfo_ = hasClientInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo) {
          return mergeFrom((com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo other) {
        if (other == com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo.getDefaultInstance()) return this;
        if (other.hasHasClientInfo()) {
          setHasClientInfo(other.getHasClientInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
    public final boolean isInitialized() {
        return true;
      }

      @Override
    public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mi.milink.sdk.proto.DownstreamPacketProto.ExtraInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean hasClientInfo_ ;
      /**
       * <code>optional bool hasClientInfo = 1;</code>
       *
       * <pre>
       * true 代表acc 缓存了 client信息
       * </pre>
       */
      @Override
    public boolean hasHasClientInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool hasClientInfo = 1;</code>
       *
       * <pre>
       * true 代表acc 缓存了 client信息
       * </pre>
       */
      @Override
    public boolean getHasClientInfo() {
        return hasClientInfo_;
      }
      /**
       * <code>optional bool hasClientInfo = 1;</code>
       *
       * <pre>
       * true 代表acc 缓存了 client信息
       * </pre>
       */
      public Builder setHasClientInfo(boolean value) {
        bitField0_ |= 0x00000001;
        hasClientInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool hasClientInfo = 1;</code>
       *
       * <pre>
       * true 代表acc 缓存了 client信息
       * </pre>
       */
      public Builder clearHasClientInfo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hasClientInfo_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mi.milink.sdk.proto.ExtraInfo)
    }

    static {
      defaultInstance = new ExtraInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mi.milink.sdk.proto.ExtraInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mi_milink_sdk_proto_DownstreamPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mi_milink_sdk_proto_DownstreamPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mi_milink_sdk_proto_ExtraInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mi_milink_sdk_proto_ExtraInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/mns_downstream.proto\022\027com.mi.mil" +
      "ink.sdk.proto\032\030proto/mns_upstream.proto\"" +
      "\343\001\n\020DownstreamPacket\022\013\n\003seq\030\001 \001(\r\022\r\n\005miU" +
      "in\030\002 \001(\004\022\017\n\007mnsCode\030\003 \001(\021\022\020\n\010busiCode\030\004 " +
      "\001(\021\022\022\n\nserviceCmd\030\005 \001(\t\022\020\n\010busiBuff\030\006 \001(" +
      "\014\022\r\n\005extra\030\007 \001(\014\022\021\n\tmnsErrMsg\030\010 \001(\t\022\r\n\005m" +
      "iUid\030\t \001(\t\0229\n\013busiControl\030\n \001(\0132$.com.mi" +
      ".milink.sdk.proto.BusiControl\"\"\n\tExtraIn" +
      "fo\022\025\n\rhasClientInfo\030\001 \001(\010B0\n\027com.mi.mili" +
      "nk.sdk.protoB\025DownstreamPacketProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          @Override
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mi.milink.sdk.proto.UpstreamPacketProto.getDescriptor(),
        }, assigner);
    internal_static_com_mi_milink_sdk_proto_DownstreamPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mi_milink_sdk_proto_DownstreamPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mi_milink_sdk_proto_DownstreamPacket_descriptor,
        new java.lang.String[] { "Seq", "MiUin", "MnsCode", "BusiCode", "ServiceCmd", "BusiBuff", "Extra", "MnsErrMsg", "MiUid", "BusiControl", });
    internal_static_com_mi_milink_sdk_proto_ExtraInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mi_milink_sdk_proto_ExtraInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mi_milink_sdk_proto_ExtraInfo_descriptor,
        new java.lang.String[] { "HasClientInfo", });
    com.mi.milink.sdk.proto.UpstreamPacketProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
